---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${PROJECT_NAME}
    env: ${RUNTIME_MARK}
  name: ${PROJECT_NAME}
  namespace: ${PROJECT_NAMESPACE}
spec:
  ports:
    - name: http
      protocol: TCP
      port: ${PROJECT_PORT}
      targetPort: ${PROJECT_PORT}
  selector:
    app: ${PROJECT_NAME}
  type: ClusterIP
